name: Build And Export

on:
  push:
    branches: [ master, develop ]

jobs:
  Godot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Export
        shell: pwsh
        run: | 
            Import-Module .\game.psm1 |
            Run-ServerExport
      - name: Build
        id: build
        uses: josephbmanley/build-godot-action@v1.4.1
        with:
          name: example
          preset: ${{ matrix.platform }}
          debugMode: "true"
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: godot-zombie-shooter-win-x64
          path: publish/winx64